document.addEventListener('DOMContentLoaded', async () => {
  const form = document.getElementById('patientInfoForm');

  // 🔹 Make all textareas auto-resize
  const textareas = form.querySelectorAll("textarea");
  textareas.forEach(textarea => {
    // Initial height adjustment
    textarea.style.height = textarea.scrollHeight + "px";

    // Auto-resize on input
    textarea.addEventListener("input", () => {
      textarea.style.height = "auto"; 
      textarea.style.height = textarea.scrollHeight + "px";
    });
  });

  // 🔹 Fetch patient info from server
  try {
    const response = await fetch('/patient-info');

    if (!response.ok) {
      throw new Error('Failed to fetch patient info');
    }

    const data = await response.json();
    const info = data.patient_info || {};

    // Populate form fields
    for (const key in info) {
      const field = form.elements.namedItem(key);
      if (field) {
        field.value = info[key] || '';
        // Adjust height if it's a textarea
        if (field.tagName.toLowerCase() === "textarea") {
          field.style.height = "auto";
          field.style.height = field.scrollHeight + "px";
        }
      }
    }
  } catch (err) {
    alert('Error loading patient info: ' + err.message);
  }

  // 🔹 Add PDF export button
  const pdfButton = document.createElement('button');
  pdfButton.textContent = "Download PDF";
  pdfButton.type = "button";
  pdfButton.style.marginTop = "20px";
  form.insertAdjacentElement("afterend", pdfButton);

  pdfButton.addEventListener("click", () => {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Doctor's Notes - Patient Info", 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  let y = 50; // 🔹 More space after title
  const lineHeight = 1;

  for (let element of form.elements) {
    if (element.name) {
      let label = element.previousElementSibling?.innerText || element.name;
      let value = element.value || "N/A";

      // Wrap long text
      let splitValue = doc.splitTextToSize(value, 120);

      // 🔹 Print label
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, y);

      doc.setFont("helvetica", "normal");
      doc.text(`${splitValue}`, label.length * 2.7 + 20, y);

      // Calculate vertical space taken by this field
      let blockHeight = splitValue.length * lineHeight;

      // 🔹 Separator line
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(20, y + blockHeight + 2, 190, y + blockHeight + 2);  // Adjusted the y position for the line

      // Move down for next field
      y += blockHeight + 6;

      // Page break if needed
      if (y > 270) {
        doc.addPage();
        y = 30;
        }
    }
  }
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Generated by Patient System", 105, 285, { align: "center" });

  // Save as PDF
  doc.save("Patient_Info.pdf");
});
});
